# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm install
      - run: npm run test
        env:
          NODE_ENV: test-remote
          JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
          JWT_PUBLIC_KEY: ${{secrets.JWT_PUBLIC_KEY}}
          JWT_ISSUER: ${{secrets.JWT_ISSUER}}
          JWT_AUDIENCE: ${{secrets.JWT_AUDIENCE}}
          JWT_EXPIRES: ${{secrets.JWT_EXPIRES}}
          JWT_ALGORITHM: ${{secrets.JWT_ALGORITHM}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          REDIS_PORT: ${{secrets.REDIS_PORT}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mcw-votes-api" #Must be unique in Heroku
          heroku_email: "mcwake-dev@outlook.com"
